package calculator;


/**
* calculator/ApplicationInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Tuesday, November 7, 2017 10:35:03 PM GMT
*/

public final class ApplicationInfo implements org.omg.CORBA.portable.IDLEntity
{
  public int version = (int)0;
  public String description = null;

  public ApplicationInfo ()
  {
  } // ctor

  public ApplicationInfo (int _version, String _description)
  {
    version = _version;
    description = _description;
  } // ctor

} // class ApplicationInfo
