package calculator;

/**
* calculator/ApplicationInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Tuesday, November 7, 2017 10:22:18 PM GMT
*/

public final class ApplicationInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public calculator.ApplicationInfo value = null;

  public ApplicationInfoHolder ()
  {
  }

  public ApplicationInfoHolder (calculator.ApplicationInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculator.ApplicationInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculator.ApplicationInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculator.ApplicationInfoHelper.type ();
  }

}
