package calculator;


/**
* calculator/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Tuesday, November 7, 2017 10:22:18 PM GMT
*/

public interface CalculatorOperations 
{
  int add (int x, int y);
  int[] getNext (int base, int howMany);
  calculator.ApplicationInfo getApplicationInfo ();
} // interface CalculatorOperations
