package calculator;


/**
* calculator/LongsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Tuesday, November 7, 2017 10:22:18 PM GMT
*/

public final class LongsHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public LongsHolder ()
  {
  }

  public LongsHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculator.LongsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculator.LongsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculator.LongsHelper.type ();
  }

}
